### ISSUE TITLE
Cannot run LWB on WizziMote(cc430f5137)

### ISSUE THREAD

**Issue by bfzhou** [ETHZ-TEC/LWB#3]
Hi there, 

I'm currently working with contiki and I want to port contiki to WizziMote, then I found this repository which adopts contiki with cc430F5137. WizziMote is also based on cc430f5137, but it does not have the XT1 crystal and some pins are different. I saw that LWB can work without XT1 using the REFO clk. 

To test LWB with WizziMote, I changed the pins for LEDs and made LEDs blink but I cannot make the UART output anything. And when I run LWB I don't see anything happens. I changed the port and pins for UART communication (P2.0 and P2.1 for WizziMote) but I don't know if it is the problem with the clock setting or baudrate. 

What necessary changes should I make in the to get the UART work for WizziMote and then port LWB to it? After seeing the output from then I guess I can test the other part of the system. 

Thanks,
Baofeng

**Comment by rdaforno** [comment]
Hi Baofeng

I assume you checked out the 'master' branch and are trying to get the 
'apps/lwb' application to run. Did you make all the changes in config.h 
or any other file?

The problem is probably not related to the clock speed since the UART is 
clocked by XT2, not XT1. Why did you change the port pins for the UART? 
Did it work with the pins unchanged? If you change the pins, you need to 
map the secondary function of those pins to UART.

Since it is the same MCU, changes to the code are only necessary if you 
use different GPIOs for different functions compared to the Olimex 
MSP-CCRF board.

Cheers,
Reto

**Comment by bfzhou** [comment]
Thank you Reto! Finally, I made it work after this long time... Thanks again for the help!
